### ISSUE TITLE
Add recipe for 'sl', 'cowsay' and 'cmatrix'

### ISSUE THREAD

**Issue by ivysochyn** [Linux-Academic-Group/meta-lag#2]
The task is to add recipes to `meta-lag` for following applications:
* sl: https://github.com/mtoyoda/sl
* cowsay: https://github.com/piuccio/cowsay
* cmatrix: https://github.com/abishekvashok/cmatrix

**Comment by ivysochyn** [comment]
The `sl` recipe was successfully implemented.

**Comment by ivysochyn** [comment]
The original `cowsay` can't be implemented yet as `nodejs` doesn't have `riscv64` support.

But there's an alternative written in `go`: https://github.com/Code-Hex/Neo-cowsay.

**Comment by GPlaczek** [comment]
There is also a `rust` alternative: https://github.com/msmith491/rust-cowsay
I don't know much about `riscv64` support in cargo though.

**Comment by ivysochyn** [comment]
The 'cmatrix' was successfully built, ported and runned on `Unmatched` board.
